---
name: PRPreClean
on:
  pull_request:
    branches:
      - "test"
    types: [ closed ]

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Pack PR info
        run: |
          echo "${{ github.event.pull_request.number }}" >> out/pr_number
          echo -n ${GITHUB_SHA} > out/pr_sha
      - name: Upload PR cleanup data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cleanup-pr${{ github.event.pull_request.number }}
          path: out/*